import PDFDocument from "pdfkit";

export function generateCertificatePdf({ studentName, courseTitle, certificateCode }) {
  const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 48 });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));
  doc.fontSize(34).text("EduPath Certificate", { align: "center" });
  doc.moveDown(1.5);
  doc.fontSize(18).text("This certifies that", { align: "center" });
  doc.moveDown();
  doc.fontSize(30).text(studentName || "Student", { align: "center" });
  doc.moveDown();
  doc.fontSize(18).text(`successfully completed ${courseTitle || "Course"}`, { align: "center" });
  doc.moveDown(2);
  doc.fontSize(12).text(`Certificate ID: ${certificateCode}`, { align: "center" });
  doc.end();

  return new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}

export function generateQuizResultPdf({ studentName, quizTitle, score, percentage, status, attemptNumber }) {
  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks = [];

  doc.on("data", (chunk) => chunks.push(chunk));
  doc.fontSize(26).text("EduPath Quiz Result", { align: "center" });
  doc.moveDown();
  doc.fontSize(16).text(`Student: ${studentName || "Student"}`);
  doc.text(`Quiz: ${quizTitle || "Quiz"}`);
  doc.text(`Attempt: #${attemptNumber || 1}`);
  doc.text(`Score: ${score || 0}`);
  doc.text(`Percentage: ${percentage || 0}%`);
  doc.text(`Status: ${status || "submitted"}`);
  doc.moveDown();
  doc.fontSize(11).fillColor("#666").text("Generated by EduPath LMS. Result calculations are performed securely on the backend.");
  doc.end();

  return new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}
