export const seedCategories = [
  { name: "Web Development", slug: "web-development", description: "Frontend and backend engineering" },
  { name: "Artificial Intelligence", slug: "artificial-intelligence", description: "AI, ML and data products" },
  { name: "Product Design", slug: "product-design", description: "UI, UX and design systems" },
];

export const seedCourses = [
  {
    title: "React Mastery: Build Modern Products",
    slug: "react-mastery-build-modern-products",
    category: "Web Development",
    level: "intermediate",
    thumbnail: "/assets/images/course/course-1/1.png",
    shortDescription: "Build production-ready React products and dashboards.",
    description: "A practical React course covering components, state, routing, APIs and product architecture.",
    pricingType: "paid",
    price: 2999,
    discountPrice: 2499,
    status: "published",
    featured: true,
    tags: ["react", "frontend", "dashboard"],
  },
  {
    title: "AI Product Strategy",
    slug: "ai-product-strategy",
    category: "Artificial Intelligence",
    level: "beginner",
    thumbnail: "/assets/images/course/course-1/2.png",
    shortDescription: "Design useful AI products and reliable workflows.",
    description: "Learn AI product discovery, prompt workflows, evaluation and learner experiences.",
    pricingType: "paid",
    price: 3999,
    discountPrice: 3499,
    status: "review_pending",
    tags: ["ai", "product"],
  },
  {
    title: "UI Design Systems Fundamentals",
    slug: "ui-design-systems-fundamentals",
    category: "Product Design",
    level: "beginner",
    thumbnail: "/assets/images/course/course-1/3.png",
    shortDescription: "Create consistent interfaces with reusable design systems.",
    description: "A beginner-friendly course for tokens, components, accessibility and handoff.",
    pricingType: "free",
    price: 0,
    status: "published",
    tags: ["design", "ui", "systems"],
  },
];
